spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${url}
    username: ${user}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${pass}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

server:
  port: 8081